# Generated by Django 5.1.1 on 2024-09-07 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(through='products.BookCategory', to='products.category'),
        ),
        migrations.AddField(
            model_name='favoritebook',
            name='id_book',
            field=models.ForeignKey(db_column='id_book', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='products.book'),
        ),
        migrations.AddField(
            model_name='favoritebook',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='id_book',
            field=models.ForeignKey(db_column='id_book', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.book'),
        ),
        migrations.AlterUniqueTogether(
            name='bookcategory',
            unique_together={('book', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='favoritebook',
            unique_together={('id_user', 'id_book')},
        ),
    ]
